version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: welocal-postgres
    environment:
      POSTGRES_USER: welocal
      POSTGRES_PASSWORD: welocal123
      POSTGRES_DB: welocal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - welocal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U welocal"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    container_name: welocal-zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: welocal
      POSTGRES_PASSWORD: welocal123
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"
    networks:
      - welocal-network
    depends_on:
      postgres:
        condition: service_healthy

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    container_name: welocal-zabbix-web
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: welocal
      POSTGRES_PASSWORD: welocal123
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - "10401:8080"
    networks:
      - welocal-network
    depends_on:
      - zabbix-server

  # welocal-ecology-service:
  #   build:
  #     context: ./welocal-ecology-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-ecology-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10402:10402"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-freemarket-service:
  #   build:
  #     context: ./welocal-freemarket-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-freemarket-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10403:10403"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-small-business-service:
  #   build:
  #     context: ./welocal-small-business-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-small-business-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10404:10404"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-farmers-service:
  #   build:
  #     context: ./welocal-farmers-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-farmers-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10405:10405"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-transport-service:
  #   build:
  #     context: ./welocal-transport-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-transport-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10406:10406"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-local-services-service:
  #   build:
  #     context: ./welocal-local-services-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-local-services-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10407:10407"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # welocal-polls-service:
  #   build:
  #     context: ./welocal-polls-service
  #     dockerfile: Dockerfile
  #   container_name: welocal-polls-service
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/welocal
  #     - SPRING_DATASOURCE_USERNAME=welocal
  #     - SPRING_DATASOURCE_PASSWORD=welocal123
  #   ports:
  #     - "10408:10408"
  #   networks:
  #     - welocal-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  welocal-auth-service:
    build:
      context: ./welocal-auth-service
      dockerfile: Dockerfile
    container_name: welocal-auth-service
    ports:
      - "10409:10409"
    networks:
      - welocal-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  welocal-network:
    driver: bridge

volumes:
  postgres_data:
